---
- name: Install and start httpd on Amazon Linux
  hosts: webservers
  become: yes  # To execute tasks as root
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present

    - name: Start the httpd service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: copy file to agent
      copy:
        src: /home/ec2-user/playbook/ansible/index2.html
        dest: /var/www/html
        owner: root
        group: root
        mode: "0644"